### ISSUE TITLE
Add Lonboard to images

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-workspaces#109]
Lonboard is a new interactive visualization tool for large amounts of vector data in python notebook environments.
https://github.com/developmentseed/lonboard

We want to add it to the MAAP envs to support visualization of data like ICESat2 and GEDI.
The tricky part is that `anywidget` has to be installed in both the `base` env, and the user end `vanilla, pangeo` etc... as this version must match so the correct JS is loaded in the browser.

Starting with just the Pangeo image would be fine. Would be good to target this for the 3.1.6 release.

@kylebarron can answer any more detailed questions. FYI @anilnatha this is similar to issues we had on stac_ipyleaflet previously.

cc: @batpad

**Comment by grallewellyn** [comment]
@wildintellect Sounds good! Just FYI our next release is 4.0.0 and I added this ticket to our to do list for that release

**Comment by wildintellect** [comment]
@grallewellyn it's been clarified that the `base` env having `anywidget ~=0.9` will make an image capable of running `lonboard`
Can you provide an update on when the 3.1.6 images will be released? We have some users who will need `lonboard` on a regular basis now.

**Comment by grallewellyn** [comment]
@wildintellect The expected release for the v4.0.0 platform release is June 26th and we will make sure this ticket gets addressed for the release 
@anilnatha Are you okay with adding `anywidget` to the `base` env? It would be the only package we add to `base` and we said we don't want to add packages to `base` anymore, but it sounds like we might need to make an exception?

**Comment by grallewellyn** [comment]
@wildintellect I built this image: 'mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/pangeo:b0b86ec' with `lonboard` and `anywidget` (I built it off a branch with a lot of other updated packages as well). I didn't add `anywidget` to the `base` env, but the notebook I wrote from `lonboard`'s documentation runs successfully (slack'ed to you). Is there something specific I can test that was failing before? Or is it possible we don't need to add `anywidget` to the `base` env?

**Comment by wildintellect** [comment]
I'll need to check with the `lonboard` author @kylebarron
It's possible if we already have `lonboard` installed that nothing else needs to be done. particularly if jupyterhub starts up with the custom env as default (e.g. `vanilla`, `pangeo` etc). What do you do to make sure that's the env that starts for users when the workspace comes up?

**Comment by kylebarron** [comment]
What is the definition of `base` here? Is that a user-facing "global" conda environment, which could be distinct from the environment from which JupyterHub itself is launched? In that case, you could consider that its own client-facing environment, and `lonboard` doesn't need to be installed there. 

But from my research and testing so far, anywidget must be installed in the environment from which JupyterHub itself is launched, and if it isn't then plots will not render.

**Comment by wildintellect** [comment]
@kylebarron thanks for the clarification. @grallewellyn can you confirm under which conda environment Jupyterhub is launched?

**Comment by grallewellyn** [comment]
> can you confirm under which conda environment Jupyterhub is launched?

`source /opt/conda/bin/activate $WORKSPACE_TYPE` in our [entrypoint.sh](https://github.com/MAAP-Project/maap-workspaces/blob/develop/jupyterlab/entrypoint.sh#L166) where WORKSPACE_TYPE is vanilla, pangeo, etc.
`base` is the default conda environment that is always named `base` in which we don't install packages anymore because it was giving us various issues. We install all user requested packages into vanilla, pangeo, etc. and that is what we recommend users to use (when you open your terminal in the ADE, vanilla, pangeo, etc. is already activated) 
I just tested and `lonboard` works in all images, and I will merge the updates with my `feature/update-packages` branch this week

**Comment by wildintellect** [comment]
Confirmed, I've tested:
- [x] pangeo image
- [x] R image
