### ISSUE TITLE
Upgrade images to use libmamba solver

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/maap-workspaces#44]

**Comment by wildintellect** [comment]
```
conda install -n base conda-libmamba-solver
conda config --set solver libmamba
```
Can always be overwritten with
```
--solver=classic
```

Question should we also be setting the default repo to `conda-forge`?

**Comment by anilnatha** [comment]
Closing this ticket as we upgraded miniconda in the last release which uses the new libmamba solver by default.
